// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd7qw-sJf3pdF4VM3uOFnR4ZgFNz6Gn54',
    appId: '1:25169885901:web:b7bcea63e44804ab748784',
    messagingSenderId: '25169885901',
    projectId: 'otchi-7e9b3',
    authDomain: 'otchi-7e9b3.firebaseapp.com',
    storageBucket: 'otchi-7e9b3.appspot.com',
    measurementId: 'G-F7BN4ZRKTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlZsPP87m9fq5y7gjti-MdrvPgVhUhyUw',
    appId: '1:25169885901:android:f77ac551b5971067748784',
    messagingSenderId: '25169885901',
    projectId: 'otchi-7e9b3',
    storageBucket: 'otchi-7e9b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDexhROQCrUNwYIo5j3QZGOs7T1h52lnvE',
    appId: '1:25169885901:ios:6edfb8a124b1f0b5748784',
    messagingSenderId: '25169885901',
    projectId: 'otchi-7e9b3',
    storageBucket: 'otchi-7e9b3.appspot.com',
    iosClientId: '25169885901-23jng30rnrqgmed7jr3r9ibcna572jif.apps.googleusercontent.com',
    iosBundleId: 'ot.com.example.ot',
  );
}
